dealer = {
    "city": "Самара",
    "where": "Самаре",
}
# Словарь соответствия цветов
model_mapping = {
    "E5": {
        "folder": "e5",
        "color": {
            "Black": "black.png",
            "Черный": "black.png",
            "Gray": "gray.png",
            "Grey": "gray.png",
            "Серый": "gray.png",
            "Red": "red.png",
            "Красный": "red.png",
            "Silver": "white.png",
            "Серебристый": "white.png",
            "Серебряный": "white.png",
            "White": "white.png",
            "Белый": "white.png",
        }},
    "X3": {
        "folder": "x3",
        "color": {
            "Black": "black.png",
            "Blue": "blue.png",
            "Dark-gray": "dark-gray.png",
            "Light-gray": "light-gray.png",
            "Grey": "light-gray.png",
            "Red": "red.png",
            "White": "white.png",
            "Черный": "black.png",
            "Синий": "blue.png",
            "Серый": "dark-gray.png",
            "Темно-серый": "dark-gray.png",
            "Светло-серый": "light-gray.png",
            "Красный": "red.png",
            "Серебристый": "white.png",
            "Белый": "white.png",
        }},
    "X3 PRO": {
        "folder": "x3pro",
        "color": {
            "Black": "black.png",
            "Blue": "blue.png",
            "Dark-gray": "dark-gray.png",
            "Light-gray": "light-gray.png",
            "Grey": "light-gray.png",
            "Red": "red.png",
            "White": "white.png",
            "Черный": "black.png",
            "Синий": "blue.png",
            "Серый": "dark-gray.png",
            "Темно-серый": "dark-gray.png",
            "Светло-серый": "light-gray.png",
            "Красный": "red.png",
            "Серебристый": "white.png",
            "Белый": "white.png",
        }},
    "X7 Kunlun": {
        "folder": "x7-kunlun",
        "color": {
            "Black": "black.png",
            "Dark-blue": "dark-blue.png",
            "Dark-gray": "dark-gray.png",
            "Light-gray": "light-gray.png",
            "Grey": "light-gray.png",
            "Purple": "purple.png",
            "White": "white.png",
            "Черный": "black.png",
            "Серый": "dark-gray.png",
            "Темно-серый": "dark-gray.png",
            "Светло-серый": "light-gray.png",
            "Синий": "dark-blue.png",
            "Темно-синий": "dark-blue.png",
            "Фиолетовый": "purple.png",
            "Серебристый": "white.png",
            "Белый": "white.png",
        }},
    # ... добавьте другие модели по мере необходимости
}